/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */

/*
 * AbilitiePanel.java Created on 2010-07-18, 03:44:50
 */

package gui.card;

import javax.swing.JLabel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import engine.card.abilities.Abiliti;

/**
 * Panel pojedynczego atrybutu przystosowany do odświerzenia
 * 
 * @author bambucha
 */
public class AbilitiPanel extends javax.swing.JPanel implements ChangeListener
{

    /** Creates new form AbilitiePanel */
    public AbilitiPanel()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        value = new javax.swing.JLabel();
        modifier = new javax.swing.JLabel();
        name = new javax.swing.JLabel();

        value.setText("10");

        modifier.setText("+0");

        name.setText("name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(name)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                .addComponent(value,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        28,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modifier).addGap(29, 29, 29)));
        layout.setVerticalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(name)
                                                .addComponent(value)
                                                .addComponent(
                                                        modifier,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        17,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel modifier;
    private javax.swing.JLabel name;
    private javax.swing.JLabel value;

    // End of variables declaration//GEN-END:variables

    @Override
    public void stateChanged(ChangeEvent e)
    {
        if (e.getSource() instanceof Abiliti)
        {
            Abiliti source = (Abiliti)e.getSource();
            value.setText(source.getValue().toString());
            modifier.setText(source.getModifier().toString());
        }

    }

    public JLabel getNameLabel()
    {
        return name;
    }
}
