/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */

/*
 * SavingThrowPanel.java Created on 2010-07-18, 08:37:40
 */

package gui.card;

/**
 * Panel zawierający rzuty obronne.
 * 
 * @author bambucha
 */
public class SavingThrowsPanel extends javax.swing.JPanel
{

    /** Creates new form SavingThrowPanel */
    public SavingThrowsPanel()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        FortitudeThrow = new gui.card.SavingThrowPanel("Fortitude");
        ReflexThrow = new gui.card.SavingThrowPanel("Reflex");
        WillThrow = new gui.card.SavingThrowPanel("Will");

        setBorder(javax.swing.BorderFactory.createTitledBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(
                        0, 0, 0), 2), "SavingThrow"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(
                                                        FortitudeThrow,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        188, Short.MAX_VALUE)
                                                .addComponent(
                                                        ReflexThrow,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        188, Short.MAX_VALUE)
                                                .addComponent(
                                                        WillThrow,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        188, Short.MAX_VALUE))
                                .addContainerGap()));
        layout.setVerticalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(FortitudeThrow,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ReflexThrow,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(WillThrow,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.card.SavingThrowPanel FortitudeThrow;
    private gui.card.SavingThrowPanel ReflexThrow;
    private gui.card.SavingThrowPanel WillThrow;

    // End of variables declaration//GEN-END:variables

    /**
     * Zwraca panel rzutu na wyrtwałość
     * 
     * @return Panel
     */
    public SavingThrowPanel getFortitudeThrow()
    {
        return FortitudeThrow;
    }

    /**
     * Zwraca panel rzutu na refleks
     * 
     * @return Panle
     */
    public SavingThrowPanel getReflexThrow()
    {
        return ReflexThrow;
    }

    /**
     * Zwraca panel rzutu na wolę
     * 
     * @return Panle
     */
    public SavingThrowPanel getWillThrow()
    {
        return WillThrow;
    }
}
